/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API usage counters
         * @description Success vs rejected provider calls.
         *
         *     Reads the same path the writer uses (METRICS_FILE) rather than a duplicated
         *     literal, so overriding API_METRICS_PATH cannot desync reader and writer.
         */
        get: operations["get_metrics_api_v1_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Persisted application settings */
        get: operations["get_settings_endpoint_api_v1_settings_get"];
        put?: never;
        /**
         * Toggle Local-Only Mode
         * @description Local-Only Mode skips every Gemini call and goes straight to the local
         *     fallback tiers, so quota can be deliberately stopped once rate-limited.
         */
        post: operations["update_settings_endpoint_api_v1_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live provider fallback state
         * @description Which models are in cooldown right now, which last succeeded, and whether
         *     Local-Only Mode is skipping all of them by choice.
         *
         *     Real current state rather than a cumulative counter: the UI previously had
         *     to guess exhaustion from a running total, which is wrong the moment a
         *     cooldown expires.
         */
        get: operations["get_models_status_api_v1_models_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start the main cohort pipeline
         * @description Returns immediately. Poll GET /run/progress, then GET /employees.
         */
        post: operations["execute_pipeline_api_v1_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/run/realtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start the realtime cohort pipeline */
        post: operations["execute_realtime_pipeline_api_v1_run_realtime_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/run/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current run progress */
        get: operations["get_run_progress_api_v1_run_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest status for the main cohort */
        get: operations["get_employees_status_api_v1_employees_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employees/realtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest status for the realtime cohort */
        get: operations["get_realtime_employees_status_api_v1_employees_realtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/employee/{name}/briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A person's latest briefing
         * @description The manager briefing from this person's most recent evaluation.
         */
        get: operations["get_employee_briefing_api_v1_employee__name__briefing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ingestion and pipeline event log
         * @description Newest first. This is the operational event log, not the access audit
         *     trail -- that is `src/governance/audit.py` and is hash-chained.
         */
        get: operations["get_history_api_v1_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear the event log
         * @description Clears the operational log only.
         *
         *     Deliberately cannot touch the governance audit trail, which is append-only
         *     at the database level. A "clear history" button that erased the record of
         *     who looked at whom would defeat the point of having one.
         */
        post: operations["clear_history_api_v1_history_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/report/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Main cohort report */
        get: operations["get_raw_report_api_v1_report_raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/report/realtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Realtime cohort report */
        get: operations["get_realtime_report_api_v1_report_realtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/report/threat-model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** STRIDE threat model */
        get: operations["get_threat_model_api_v1_report_threat_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete all main-cohort evaluations */
        post: operations["clear_pipeline_data_api_v1_memory_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memory/clear/realtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete all realtime-cohort data */
        post: operations["clear_realtime_data_api_v1_memory_clear_realtime_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest pasted CSV text
         * @description Rows are merged by employee name, so re-pasting someone replaces their
         *     row rather than duplicating it. A `week` column in the pasted content routes
         *     each row to its own week, so one paste can cover a multi-week export.
         */
        post: operations["ingest_raw_csv_api_v1_ingest_raw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest an uploaded CSV file */
        post: operations["ingest_uploaded_csv_api_v1_ingest_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a signed JSON payload
         * @description Authenticated by HMAC over the raw body in the security middleware, since
         *     the sender is a system that cannot hold a rotating bearer token.
         */
        post: operations["ingest_webhook_api_v1_ingest_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync from the local SQLite database
         * @description `table_name` is passed as a parameterised value, never interpolated into
         *     SQL, so it never needs sanitising.
         *
         *     There is no corporate Postgres behind this: it is a real local database with
         *     real persistence, seeded with a demo batch on each sync. Recorded in
         *     docs/LIMITATIONS.md rather than implied to be a live enterprise system.
         */
        post: operations["ingest_from_db_api_v1_ingest_db_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/db/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Local database statistics */
        get: operations["get_db_status_api_v1_ingest_db_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/s3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync from an object store URI
         * @description A genuine boto3 GetObject when AWS credentials are present; otherwise a
         *     real local folder mirroring the S3 key layout. Dropping a CSV there and
         *     syncing genuinely reads that file.
         */
        post: operations["ingest_from_s3_api_v1_ingest_s3_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/s3/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Local bucket statistics */
        get: operations["get_bucket_status_api_v1_ingest_s3_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/natural-language": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a free-text description
         * @description Gemini first, then a local regex extractor.
         *
         *     The fallback means natural-language ingest keeps working entirely offline
         *     rather than returning a 500, and the response says which produced it --
         *     an extraction from a rule-based parser and one from a model must not be
         *     indistinguishable to whoever reads the result.
         */
        post: operations["ingest_natural_language_api_v1_ingest_natural_language_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/score/custom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate one hypothetical employee-week
         * @description Runs the real agent chain against made-up numbers.
         *
         *     Writes to an isolated scratch directory so a what-if run can never overwrite
         *     a real employee's memory files -- the default simulator name is also a real
         *     employee in the demo cohort, and that collision would silently corrupt one
         *     person's actual history.
         */
        post: operations["score_custom_employee_api_v1_score_custom_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mock-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate the synthetic demo cohort
         * @description Writes four weekly CSVs and matching memory files. DESTRUCTIVE.
         *
         *     Emits exactly CANONICAL_HEADER. This generator previously wrote sick_days,
         *     task_accuracy and sentiment, so it kept re-creating prohibited columns on
         *     disk even after they were removed from the allowlist -- the reason
         *     `test_mock_generator_emits_only_canonical_columns` exists.
         */
        post: operations["generate_mock_data_api_v1_mock_data_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a manager's verdict on a briefing
         * @description The ground-truth signal this system otherwise has no way to obtain.
         */
        post: operations["submit_feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interventions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record what kind of action a manager took */
        post: operations["submit_intervention_api_v1_interventions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interventions/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The closed list of recordable action types */
        get: operations["intervention_types_api_v1_interventions_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interventions/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What followed each kind of action (association, never causation)
         * @description Aggregate outcomes by intervention TYPE.
         *
         *     Never by manager. A per-manager effectiveness score would make this a
         *     performance tool for managers whose KPI is their reports' wellbeing metrics,
         *     which creates an immediate incentive to lean on whoever's numbers look bad.
         */
        get: operations["intervention_outcomes_api_v1_interventions_outcomes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is the system actually right?
         * @description Lifetime and recent calibration, reported separately.
         *
         *     A tool that was accurate for six months and has been wrong for three weeks
         *     shows up as drift here rather than being averaged into a comfortable
         *     lifetime figure.
         *
         *     Returns the tracker's own view rather than a dict rebuilt from it: the
         *     rebuild was one hand-copied field list away from disagreeing with the object
         *     it was copying.
         */
        get: operations["get_calibration_api_v1_calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registered scoring models and which one is live */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Ack
         * @description A mutation that either worked or raised. There is no partial success.
         */
        Ack: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * ApiCounters
         * @description Provider calls that succeeded, and ones the provider refused.
         */
        ApiCounters: {
            /**
             * Success
             * @default 0
             */
            success: number;
            /**
             * Rejected
             * @default 0
             */
            rejected: number;
        };
        /** AppSettings */
        AppSettings: {
            /**
             * Local Only Mode
             * @default false
             */
            local_only_mode: boolean;
        };
        /**
         * Attribution
         * @description How much one metric contributed to the score, and which way.
         *
         *     Required by 6.1's counterfactual layer: a briefing has to be able to say WHY,
         *     and a wrong call has to be debuggable. A score with no attribution is an
         *     accusation with no evidence attached.
         */
        Attribution: {
            /** Metric */
            metric: string;
            /** Contribution */
            contribution: number;
            /** Effect Size */
            effect_size: number;
            /**
             * Direction
             * @default
             */
            direction: string;
            /**
             * Weeks
             * @default []
             */
            weeks: number[];
        };
        /** Body_ingest_uploaded_csv_api_v1_ingest_upload_post */
        Body_ingest_uploaded_csv_api_v1_ingest_upload_post: {
            /** Week Number */
            week_number: number;
            /** File */
            file: string;
        };
        /**
         * BriefingView
         * @description A person's most recent manager briefing, or a note saying there is none.
         */
        BriefingView: {
            /** Found */
            found: boolean;
            /**
             * Briefing
             * @default
             */
            briefing: string;
            /**
             * Raw Card
             * @default
             */
            raw_card: string;
        };
        /**
         * BucketStats
         * @description The local bucket folder, and whether real AWS credentials are present.
         */
        BucketStats: {
            /**
             * Exists
             * @default false
             */
            exists: boolean;
            /**
             * Object Count
             * @default 0
             */
            object_count: number;
            /** Objects */
            objects: string[];
            /**
             * Aws Credentials Configured
             * @default false
             */
            aws_credentials_configured: boolean;
        };
        /**
         * CalibrationReport
         * @description Whether the system's confident calls correspond to reality.
         *
         *     "A system that quietly becomes miscalibrated is worse than no system" (6.2).
         *     Worse, specifically, because people act on it: an uncalibrated tool that
         *     nobody trusts gets ignored, while an uncalibrated tool that everybody trusts
         *     changes how managers treat their reports.
         */
        CalibrationReport: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Accurate
             * @default 0
             */
            accurate: number;
            /**
             * Not Accurate
             * @default 0
             */
            not_accurate: number;
            /**
             * Harmful
             * @default 0
             */
            harmful: number;
            /** Elevated Precision */
            elevated_precision?: number | null;
            /**
             * Harm Rate
             * @default 0
             */
            harm_rate: number;
            /** System Fault Rate */
            system_fault_rate?: number | null;
        };
        /**
         * Classification
         * @enum {string}
         */
        Classification: "Healthy" | "Watch" | "At Risk" | "Silent Exit";
        /** ClearResult */
        ClearResult: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Files Removed
             * @default 0
             */
            files_removed: number;
        };
        /**
         * Confidence
         * @description How much weight the evidence can actually carry.
         *
         *     This is not decoration. A manager shown "6/10, At Risk" acts on it; a manager
         *     shown "6/10, but we have two weeks of patchy data" asks a question instead.
         *     The second conversation is the one this system exists to cause.
         * @enum {string}
         */
        Confidence: "none" | "low" | "moderate" | "high";
        /** CustomEvaluatorInput */
        CustomEvaluatorInput: {
            /** Name */
            name: string;
            /** Week Number */
            week_number: number;
            /** Tasks Completed */
            tasks_completed: number;
            /** Avg Response Time */
            avg_response_time: number;
            /** After Hours Logins */
            after_hours_logins: number;
            /**
             * Previous Classification
             * @default Healthy
             */
            previous_classification: string;
            /**
             * Consecutive Weeks Elevated
             * @default 0
             */
            consecutive_weeks_elevated: number;
            /**
             * Weekly Hours
             * @default 40
             */
            weekly_hours: number;
        };
        /**
         * DatabaseStats
         * @description The real local SQLite file. There is no corporate database behind this.
         */
        DatabaseStats: {
            /**
             * Exists
             * @default false
             */
            exists: boolean;
            /**
             * Total Rows
             * @default 0
             */
            total_rows: number;
            /**
             * Distinct Tables
             * @default 0
             */
            distinct_tables: number;
            /**
             * Distinct Weeks
             * @default 0
             */
            distinct_weeks: number;
            /**
             * File Size Bytes
             * @default 0
             */
            file_size_bytes: number;
            /** Last Ingested At */
            last_ingested_at: string | null;
        };
        /** DatabaseSyncInput */
        DatabaseSyncInput: {
            /**
             * Db Url
             * @default
             */
            db_url: string;
            /**
             * Table Name
             * @default
             */
            table_name: string;
            /** Target Week */
            target_week: number;
        };
        /** DatabaseSyncResult */
        DatabaseSyncResult: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
            /**
             * Source
             * @default sqlite
             */
            source: string;
            db_stats: components["schemas"]["DatabaseStats"] | null;
        };
        /**
         * DriftView
         * @description Lifetime vs recent calibration, and whether the gap needs attention.
         */
        DriftView: {
            overall: components["schemas"]["CalibrationReport"];
            recent: components["schemas"]["CalibrationReport"];
            /**
             * Active Model Version
             * @default
             */
            active_model_version: string;
            /**
             * Review Required
             * @default false
             */
            review_required: boolean;
            /**
             * Drifting
             * @default false
             */
            drifting: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * EmployeeSummary
         * @description A person's latest evaluation, with their own history attached.
         *
         *     `score_range` is deliberately not called a confidence interval, and it is
         *     absent rather than empty when there is none: an empty array is truthy in
         *     JavaScript, so the previous `[]` made the UI offer a range with no numbers
         *     in it.
         */
        EmployeeSummary: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            classification: components["schemas"]["Classification"];
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Latest Week */
            latest_week: number;
            /** Signals */
            signals: components["schemas"]["Signal"][];
            confidence: components["schemas"]["Confidence"] | null;
            /** Score Range */
            score_range: [
                number,
                number
            ] | null;
            /** Attributions */
            attributions: components["schemas"]["Attribution"][];
            /** Model Version */
            model_version: string | null;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** History */
            history: components["schemas"]["EmployeeWeek"][];
        };
        /**
         * EmployeeWeek
         * @description One point on a person's own history line.
         */
        EmployeeWeek: {
            /** Week */
            week: number;
            /** Score */
            score: number;
            classification: components["schemas"]["Classification"];
        };
        /**
         * EventLogEntry
         * @description One line of the operational event log.
         *
         *     The field is `action`. It was `event_type` in the hand-written frontend
         *     types, which is the drift these models exist to make impossible.
         */
        EventLogEntry: {
            /**
             * Timestamp
             * @default
             */
            timestamp: string;
            /**
             * Action
             * @default
             */
            action: string;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ExhaustedModel */
        ExhaustedModel: {
            /** Model */
            model: string;
            /**
             * Cooldown Remaining Seconds
             * @default 0
             */
            cooldown_remaining_seconds: number;
        };
        /**
         * ExtractedMetrics
         * @description What was read out of a free-text description. Nothing is inferred.
         */
        ExtractedMetrics: {
            /** Name */
            name: string;
            /**
             * Tasks Completed
             * @default 0
             */
            tasks_completed: number;
            /**
             * Avg Response Time
             * @default 0
             */
            avg_response_time: number;
            /**
             * After Hours Logins
             * @default 0
             */
            after_hours_logins: number;
            /**
             * Weekly Hours
             * @default 40
             */
            weekly_hours: number;
        };
        /** FeedbackAck */
        FeedbackAck: {
            /**
             * Status
             * @default recorded
             * @constant
             */
            status: "recorded";
            /** Week */
            week: number;
            verdict: components["schemas"]["FeedbackVerdict"];
            /**
             * Model Version
             * @default
             */
            model_version: string;
        };
        /**
         * FeedbackInput
         * @description A manager's verdict on one briefing.
         *
         *     No free-text field, by design. A notes box on a form about an employee is
         *     where health details and character judgements end up -- not through bad
         *     faith, but because a manager trying to be helpful writes them. CONTEXT.md
         *     rule 5 forbids that in agent memory, so the schema makes it impossible.
         */
        FeedbackInput: {
            /** Employee Name */
            employee_name: string;
            /** Week */
            week: number;
            verdict: components["schemas"]["FeedbackVerdict"];
            /**
             * Reason
             * @default not_stated
             */
            reason: string;
        };
        /**
         * FeedbackVerdict
         * @enum {string}
         */
        FeedbackVerdict: "accurate" | "not_accurate" | "harmful";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestResult
         * @description The outcome of one ingest call, whichever source it came from.
         */
        IngestResult: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
        };
        /** InterventionAck */
        InterventionAck: {
            /**
             * Status
             * @default recorded
             * @constant
             */
            status: "recorded";
            /** Week */
            week: number;
            intervention: components["schemas"]["InterventionType"];
        };
        /**
         * InterventionAggregate
         * @description What tends to follow one KIND of action, across many people.
         */
        InterventionAggregate: {
            intervention: components["schemas"]["InterventionType"];
            /** Sample Size */
            sample_size: number;
            /** Median Excess Recovery */
            median_excess_recovery?: number | null;
            /**
             * Improved
             * @default 0
             */
            improved: number;
            /**
             * Declined
             * @default 0
             */
            declined: number;
            /**
             * No Change
             * @default 0
             */
            no_change: number;
            /**
             * Reportable
             * @default false
             */
            reportable: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * InterventionExample
         * @description One measured outcome, with the sentence a manager should read instead.
         */
        InterventionExample: {
            /** Subject Id */
            subject_id: string;
            /** Week */
            week: number;
            intervention: components["schemas"]["InterventionType"];
            /** Metric */
            metric: string;
            /** Observed Recovery */
            observed_recovery: number;
            /** Expected From Regression */
            expected_from_regression: number;
            /** Excess Recovery */
            excess_recovery: number;
            /** Post Weeks */
            post_weeks: number;
            /** @default low */
            confidence: components["schemas"]["Confidence"];
            /**
             * Association Only
             * @default true
             */
            association_only: boolean;
            /**
             * Plain English
             * @default
             */
            plain_english: string;
        };
        /**
         * InterventionInput
         * @description What kind of action a manager took after a briefing.
         *
         *     Also has no free-text field, and for a stronger reason: text here would be
         *     the contents of a private conversation between a manager and their report.
         *     See the feasibility note at the top of src/domain/intervention.py.
         */
        InterventionInput: {
            /** Employee Name */
            employee_name: string;
            /** Week */
            week: number;
            /** Intervention */
            intervention: string;
        };
        /**
         * InterventionOutcomes
         * @description Aggregated by TYPE of action, never by manager.
         */
        InterventionOutcomes: {
            /**
             * Association Only
             * @default true
             * @constant
             */
            association_only: true;
            /**
             * Caveat
             * @default
             */
            caveat: string;
            /** By Type */
            by_type: components["schemas"]["InterventionAggregate"][];
            /**
             * Measured Outcomes
             * @default 0
             */
            measured_outcomes: number;
            /** Examples */
            examples: components["schemas"]["InterventionExample"][];
        };
        /**
         * InterventionType
         * @description What the manager did. A closed list, for the same reason as
         *     `FeedbackReason`: a free-text box here would collect the contents of a
         *     private conversation.
         * @enum {string}
         */
        InterventionType: "check_in" | "workload_adjustment" | "role_or_goal_clarification" | "blocker_removed" | "time_off_encouraged" | "connected_to_support" | "team_or_project_change" | "no_action_taken";
        /**
         * InterventionTypes
         * @description A closed list. Free text here would record a private conversation.
         */
        InterventionTypes: {
            /** Types */
            types: components["schemas"]["InterventionType"][];
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * MockDataInput
         * @description Optional seed. Omit it for the reproducible default cohort.
         */
        MockDataInput: {
            /** Seed */
            seed?: number | null;
        };
        /**
         * MockDataResult
         * @description The seed is returned so a cohort can be reproduced exactly.
         */
        MockDataResult: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Seed */
            seed: number;
        };
        /** ModelList */
        ModelList: {
            /**
             * Active
             * @default
             */
            active: string;
            /** Versions */
            versions: components["schemas"]["ModelVersion"][];
        };
        /**
         * ModelVersion
         * @description One registered scoring model and the evidence for trusting it.
         */
        ModelVersion: {
            /** Version */
            version: string;
            /** Created At */
            created_at: string;
            /**
             * Trained On Weeks
             * @default 0
             */
            trained_on_weeks: number;
            /**
             * Trained On Feedback
             * @default 0
             */
            trained_on_feedback: number;
            holdout?: components["schemas"]["CalibrationReport"] | null;
            /**
             * Holdout Size
             * @default 0
             */
            holdout_size: number;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** NaturalLanguageInput */
        NaturalLanguageInput: {
            /** Week Number */
            week_number: number;
            /** Text Prompt */
            text_prompt: string;
        };
        /**
         * NaturalLanguageResult
         * @description Carries `source` because a rule-based extraction and a model's must not
         *     be indistinguishable to whoever reads the result.
         */
        NaturalLanguageResult: {
            /** Success */
            success: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "llm" | "local-fallback";
            extracted: components["schemas"]["ExtractedMetrics"];
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
        };
        /** ObjectStoreSyncResult */
        ObjectStoreSyncResult: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
            /**
             * Source
             * @default
             */
            source: string;
        };
        /**
         * ProviderStatus
         * @description Which models are usable right now, not a cumulative counter.
         */
        ProviderStatus: {
            /** Fallback Sequence */
            fallback_sequence: string[];
            /** Last Successful Model */
            last_successful_model: string | null;
            /** Exhausted Models */
            exhausted_models: components["schemas"]["ExhaustedModel"][];
            /**
             * Local Only Mode
             * @default false
             */
            local_only_mode: boolean;
        };
        /** RawCSVInput */
        RawCSVInput: {
            /** Week Number */
            week_number: number;
            /** Csv Content */
            csv_content: string;
        };
        /**
         * RiskData
         * @description The scorer's own output for a hypothetical week, passed through.
         *
         *     Permissive on purpose: this is whatever the active tier produced, and the
         *     what-if panel renders it rather than reasoning about it.
         */
        RiskData: {
            /** Score */
            score: number | null;
            /** Classification */
            classification: string | null;
            /** Rationale */
            rationale: string | null;
            /** Confidence */
            confidence: string | null;
            /** Model Version */
            model_version: string | null;
            /** Provenance */
            provenance: string | null;
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * RunProgress
         * @description Where the current run has got to. All zeros when nothing is running.
         */
        RunProgress: {
            /** Running */
            running: boolean;
            /** Scope */
            scope: string | null;
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Current
             * @default
             */
            current: string;
            /** Error */
            error: string | null;
        };
        /**
         * RunStarted
         * @description A run was accepted. It has not finished -- poll GET /run/progress.
         */
        RunStarted: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Started
             * @default true
             */
            started: boolean;
        };
        /** S3SyncInput */
        S3SyncInput: {
            /** S3 Uri */
            s3_uri: string;
            /** Target Week */
            target_week: number;
        };
        /** SettingsUpdateInput */
        SettingsUpdateInput: {
            /** Local Only Mode */
            local_only_mode: boolean;
        };
        /**
         * Signal
         * @description One detected behavioural pattern, in the shape it was stored in.
         *
         *     Two shapes reach this model and both are real: `signal_name` from the trend
         *     detector, and `signal` from the orchestrator's MISSING_DATA_GAP marker.
         *     Neither is required, because a record written by an earlier run may carry
         *     only the other, and a 500 on the cohort view is a worse outcome than a field
         *     the UI has to fall back on.
         */
        Signal: {
            /** Signal Name */
            signal_name: string | null;
            /** Signal */
            signal: string | null;
            /** Severity */
            severity: string | null;
            /** Weeks Detected */
            weeks_detected: number[];
            /** Details */
            details: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SimulationResult
         * @description A hypothetical employee-week, scored by the real agent chain.
         */
        SimulationResult: {
            /** Success */
            success: boolean;
            /** Employee Name */
            employee_name: string;
            /** Signals */
            signals: components["schemas"]["Signal"][];
            risk_data: components["schemas"]["RiskData"];
            /**
             * Briefing
             * @default
             */
            briefing: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebhookIngestInput */
        WebhookIngestInput: {
            /** Week Number */
            week_number: number;
            /** Records */
            records: components["schemas"]["WebhookMetricRecord"][];
        };
        /** WebhookMetricRecord */
        WebhookMetricRecord: {
            /** Employee Name */
            employee_name: string;
            /** Week Number */
            week_number?: number | null;
            /**
             * Tasks Completed
             * @default 0
             */
            tasks_completed: number;
            /**
             * Avg Response Time Hours
             * @default 0
             */
            avg_response_time_hours: number;
            /**
             * After Hours Logins
             * @default 0
             */
            after_hours_logins: number;
            /**
             * Weekly Hours
             * @default 40
             */
            weekly_hours: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_metrics_api_v1_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiCounters"];
                };
            };
        };
    };
    get_settings_endpoint_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettings"];
                };
            };
        };
    };
    update_settings_endpoint_api_v1_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_models_status_api_v1_models_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatus"];
                };
            };
        };
    };
    execute_pipeline_api_v1_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStarted"];
                };
            };
        };
    };
    execute_realtime_pipeline_api_v1_run_realtime_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStarted"];
                };
            };
        };
    };
    get_run_progress_api_v1_run_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunProgress"];
                };
            };
        };
    };
    get_employees_status_api_v1_employees_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeSummary"][];
                };
            };
        };
    };
    get_realtime_employees_status_api_v1_employees_realtime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeSummary"][];
                };
            };
        };
    };
    get_employee_briefing_api_v1_employee__name__briefing_get: {
        parameters: {
            query?: {
                scope?: string;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_v1_history_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventLogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_history_api_v1_history_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ack"];
                };
            };
        };
    };
    get_raw_report_api_v1_report_raw_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/plain": unknown;
                };
            };
        };
    };
    get_realtime_report_api_v1_report_realtime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The report file. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/plain": unknown;
                };
            };
        };
    };
    get_threat_model_api_v1_report_threat_model_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/markdown": unknown;
                };
            };
        };
    };
    clear_pipeline_data_api_v1_memory_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearResult"];
                };
            };
        };
    };
    clear_realtime_data_api_v1_memory_clear_realtime_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearResult"];
                };
            };
        };
    };
    ingest_raw_csv_api_v1_ingest_raw_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RawCSVInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_uploaded_csv_api_v1_ingest_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_uploaded_csv_api_v1_ingest_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_webhook_api_v1_ingest_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookIngestInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_from_db_api_v1_ingest_db_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatabaseSyncInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseSyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_db_status_api_v1_ingest_db_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseStats"];
                };
            };
        };
    };
    ingest_from_s3_api_v1_ingest_s3_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["S3SyncInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectStoreSyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bucket_status_api_v1_ingest_s3_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketStats"];
                };
            };
        };
    };
    ingest_natural_language_api_v1_ingest_natural_language_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NaturalLanguageInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NaturalLanguageResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_custom_employee_api_v1_score_custom_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomEvaluatorInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_mock_data_api_v1_mock_data_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MockDataInput"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockDataResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_intervention_api_v1_interventions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterventionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    intervention_types_api_v1_interventions_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionTypes"];
                };
            };
        };
    };
    intervention_outcomes_api_v1_interventions_outcomes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterventionOutcomes"];
                };
            };
        };
    };
    get_calibration_api_v1_calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftView"];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
        };
    };
}
