// frontend/src/api/types.ts
//
// The names the app imports, every one of them derived from the backend
// (§4: "types and API client generated from the backend OpenAPI schema...
// a backend schema change that breaks the frontend must fail tsc in CI").
//
// `schema.ts` is generated by `npm run generate:api` from `openapi.json`, which
// `scripts/export_openapi.py` writes from the running app. Nothing in that
// chain is hand-copied, so there is no way to describe an API that is not
// served. This file adds no shapes of its own -- it only gives the generated
// types the names the pages use, anchored to the ROUTE each one comes back
// from, so a renamed field or a dropped route fails here first.
//
// It used to be different, and the difference is why this exists. Handlers were
// annotated `-> dict`, so the generated types said "some object" for every
// response and the shapes below were written out by hand. `HistoryEvent` had a
// field called `event_type`; the event log has always written `action`. The
// History page rendered an em-dash in the Type column of every row, the unit
// test mocked the same wrong field and passed, and `tsc` had nothing to
// disagree with. Response models on the handlers closed that
// (src/api/schemas/).

import type { paths } from "./schema";

// --- the two generic accessors ----------------------------------------------

/** Every path the API actually serves. A removed route fails `tsc` here. */
export type ApiPath = keyof paths;

type RequestBodyOf<P extends ApiPath, M extends keyof paths[P]> = paths[P][M] extends {
  requestBody: { content: { "application/json": infer B } };
}
  ? B
  : never;

type ResponseOf<P extends ApiPath, M extends keyof paths[P]> = paths[P][M] extends {
  responses: { 200: { content: { "application/json": infer R } } };
}
  ? R
  : never;

// --- request bodies ---------------------------------------------------------

export type FeedbackInput = RequestBodyOf<"/api/v1/feedback", "post">;
export type InterventionInput = RequestBodyOf<"/api/v1/interventions", "post">;
export type SettingsInput = RequestBodyOf<"/api/v1/settings", "post">;
export type CustomScoreInput = RequestBodyOf<"/api/v1/score/custom", "post">;
export type RawCSVInput = RequestBodyOf<"/api/v1/ingest/raw", "post">;

// --- responses --------------------------------------------------------------

export type EmployeeSummary = ResponseOf<"/api/v1/employees", "get">[number];
export type CalibrationView = ResponseOf<"/api/v1/calibration", "get">;
export type InterventionOutcomes = ResponseOf<
  "/api/v1/interventions/outcomes",
  "get"
>;
export type HistoryEvent = ResponseOf<"/api/v1/history", "get">[number];
export type RunProgress = ResponseOf<"/api/v1/run/progress", "get">;
export type ProviderStatus = ResponseOf<"/api/v1/models/status", "get">;
export type SimulationResult = ResponseOf<"/api/v1/score/custom", "post">;
export type BriefingView = ResponseOf<
  "/api/v1/employee/{name}/briefing",
  "get"
>;
export type IngestResult = ResponseOf<"/api/v1/ingest/raw", "post">;
export type RunStarted = ResponseOf<"/api/v1/run", "post">;

// --- the pieces those responses are made of ---------------------------------
//
// Reached through the response they arrive in rather than through
// `components["schemas"]`, so each name stays tied to the route that actually
// carries it. A field the backend stops sending breaks the alias, not just its
// use site.

export type Classification = EmployeeSummary["classification"];
export type Confidence = NonNullable<EmployeeSummary["confidence"]>;
export type Signal = NonNullable<EmployeeSummary["signals"]>[number];
export type Attribution = NonNullable<EmployeeSummary["attributions"]>[number];
export type EmployeeWeek = NonNullable<EmployeeSummary["history"]>[number];

export type CalibrationReport = CalibrationView["overall"];
export type InterventionAggregate = NonNullable<
  InterventionOutcomes["by_type"]
>[number];

/** The three verdicts a manager can give. Closed on the backend, not here. */
export type FeedbackVerdict = FeedbackInput["verdict"];
