// frontend/src/api/types.ts
//
// Response shapes, derived from the backend OpenAPI schema wherever it carries
// them (§4: "types and API client generated from the backend OpenAPI schema...
// a backend schema change that breaks the frontend must fail tsc in CI").
//
// `schema.ts` is generated by `npm run generate:api` from `openapi.json`, which
// `scripts/export_openapi.py` writes from the running app. The chain has no
// hand-copied link in it, so the types cannot describe an API that is not
// served.
//
// The gap, stated honestly: most handlers are annotated `-> dict`, so the
// generated schema types their responses as an open object. That makes
// `schema.ts` authoritative for PATHS, METHODS and REQUEST BODIES -- a renamed
// route or a changed payload does fail `tsc` -- but not yet for response
// fields. Closing that means response_model= on each handler, which is its own
// piece of work; recorded in docs/LIMITATIONS.md rather than left implied.
// Until then the response interfaces below are the single place those shapes
// are written down.

import type { paths } from "./schema";

// --- Generated: paths and request bodies are checked against the backend -----

/** Every path the API actually serves. A removed route fails `tsc` here. */
export type ApiPath = keyof paths;

type RequestBodyOf<P extends ApiPath, M extends keyof paths[P]> = paths[P][M] extends {
  requestBody: { content: { "application/json": infer B } };
}
  ? B
  : never;

export type FeedbackInput = RequestBodyOf<"/api/v1/feedback", "post">;
export type InterventionInput = RequestBodyOf<"/api/v1/interventions", "post">;
export type SettingsInput = RequestBodyOf<"/api/v1/settings", "post">;
export type CustomScoreInput = RequestBodyOf<"/api/v1/score/custom", "post">;
export type RawCSVInput = RequestBodyOf<"/api/v1/ingest/raw", "post">;

// --- Hand-written: response shapes, until handlers carry response models -----

export type Confidence = "none" | "low" | "moderate" | "high";
export type Classification = "Healthy" | "Watch" | "At Risk" | "Silent Exit";
export type FeedbackVerdict = "accurate" | "not_accurate" | "harmful";

export interface Attribution {
  metric: string;
  contribution: number;
  effect_size: number;
  direction: string;
  weeks: number[];
}

export interface Signal {
  signal_name?: string;
  signal?: string;
  severity?: string;
  weeks_detected?: number[];
  details?: string;
}

export interface EmployeeWeek {
  week: number;
  score: number;
  classification: Classification;
}

export interface EmployeeSummary {
  name: string;
  score: number;
  classification: Classification;
  rationale: string;
  latest_week: number;
  signals: Signal[];
  confidence: Confidence | null;
  score_range: [number, number] | null;
  attributions: Attribution[];
  model_version: string | null;
  degraded: boolean;
  history: EmployeeWeek[];
}

export interface CalibrationReport {
  total: number;
  accurate: number;
  not_accurate: number;
  harmful: number;
  elevated_precision: number | null;
  harm_rate: number;
  system_fault_rate: number | null;
}

export interface CalibrationView {
  active_model_version: string;
  overall: CalibrationReport;
  recent: CalibrationReport;
  drifting: boolean;
  review_required: boolean;
  message: string;
}

export interface InterventionAggregate {
  intervention: string;
  sample_size: number;
  median_excess_recovery: number | null;
  improved: number;
  declined: number;
  no_change: number;
  reportable: boolean;
  note: string;
}

export interface InterventionOutcomes {
  association_only: true;
  caveat: string;
  by_type: InterventionAggregate[];
  measured_outcomes: number;
  examples: Array<{
    subject_id: string;
    week: number;
    intervention: string;
    metric: string;
    excess_recovery: number;
    plain_english: string;
  }>;
}

export interface HistoryEvent {
  timestamp?: string;
  event_type?: string;
  source?: string;
  detail?: string;
  success?: boolean;
}

export interface RunProgress {
  running: boolean;
  scope: string | null;
  done: number;
  total: number;
  current: string | null;
  error: string | null;
}

export interface ProviderStatus {
  local_only_mode: boolean;
  [key: string]: unknown;
}
